version: 2
jobs:
  build-8.0.2:
    docker:
      - image: fpco/stack-build:lts-9.14

    working_directory: /home/stackage

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - restore_cache:
          key: v2-cache-1
      - run: stack build --test --only-dependencies --no-terminal --system-ghc
      - save_cache:
          key: v2-cache-1
          paths:
            - ~/.stack
            - ~/.stack-work
      - run: stack install --test --no-terminal --system-ghc
      - store_test_results:
          path: ~/.stack-work/logs/*

  build-8.0.2-osx:
    macos:
      xcode: "9.0"

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - restore_cache:
          key: v2-cache-osx-1
      - run: curl -sSL https://get.haskellstack.org/ | sh
      - run: stack build --test --only-dependencies --no-terminal --system-ghc
      - save_cache:
          key: v2-cache-osx-1
          paths:
            - ~/.stack
            - ~/.stack-work
      - run: stack install --test --no-terminal --system-ghc
      - store_test_results:
          path: ~/.stack-work/logs/*

  build-7.10.3:
    docker:
      - image: fpco/stack-build:lts-6

    working_directory: /home/stackage

    environment:
      - TEST_RESULTS: /tmp/test-results
      - STACK_YAML: stack.ghc7.10.yaml

    steps:
      - checkout
      - restore_cache:
          key: v2-cache-710-1
      - run: stack build --test --only-dependencies --no-terminal --system-ghc
      - save_cache:
          key: v2-cache-710-1
          paths:
            - ~/.stack
            - ~/.stack-work
      - run: stack install --test --no-terminal --system-ghc
      - store_test_results:
          path: ~/.stack-work/logs/*

  build-7.10.3-osx:
    macos:
      xcode: "9.0"

    working_directory: /home/stackage

    environment:
      - TEST_RESULTS: /tmp/test-results
      - STACK_YAML: stack.ghc7.10.yaml

    steps:
      - checkout
      - restore_cache:
          key: v2-cache-710-osx-1
      - run: curl -sSL https://get.haskellstack.org/ | sh
      - run: stack build --test --only-dependencies --no-terminal --system-ghc
      - save_cache:
          key: v2-cache-710-osx-1
          paths:
            - ~/.stack
            - ~/.stack-work
      - run: stack install --test --no-terminal --system-ghc
      - store_test_results:
          path: ~/.stack-work/logs/*

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-7.10.3
      - build-7.10.3-osx
      - build-8.0.2
      - build-8.0.2-osx

